### ISSUE TITLE
 API error ERROR_ZERO_CAPTCHA_FILESIZE: The size of the captcha you are uploading is less than 100 bytes

### ISSUE THREAD

**Issue by ersumitchh** [Akshit-WTF/cowin#2]
Bro, Good work.
Please fix this also captcha size.

**Comment by Akshit-WTF** [comment]
Thank you for the appreciation. Could you please post the complete error log from the console?

**Comment by ersumitchh** [comment]
This is what I can see in my logs:
Received API error ERROR_ZERO_CAPTCHA_FILESIZE: The size of the captcha you are uploading is less than 100 bytes
(node:6555) UnhandledPromiseRejectionWarning: ERROR_ZERO_CAPTCHA_FILESIZE
(Use `node --trace-warnings ...` to show where the warning was created)


Seems error while uploading captcha to https://anti-captcha.com/

**Comment by Akshit-WTF** [comment]
The thing is, I have never come across this error. I'll try reproducing it and then patch it.

**Comment by ersumitchh** [comment]
Yeah, yesterday it was not coming.
Started coming from today only.

**Comment by Akshit-WTF** [comment]
I am not sure but I think aba4d56 should fix this issue. I am unable to test at this time.

**Comment by Akshit-WTF** [comment]
![image](https://user-images.githubusercontent.com/16484140/118512299-4eaa9180-b750-11eb-8904-144746cefa9c.png)
Fixed.

**Comment by ersumitchh** [comment]
Thanks
